logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.auth0.example: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: BAlNLiE1MPA6lIfsJYBxj9PsY2XKUdN7
            client-secret: 1Lv47S60dB7TInlxYoxGNFDCm-sa5DV_ymu6FnhJADArQrM4F0SZOwJ0LrEbGaLH
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: https://dev-pbi3csp88xs4ezg5.us.auth0.com/

