logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.auth0.example: TRACE

org:
  springframework:
    cloud:
      bindings:
        boot:
          oauth2:
            enable: true



          enable=true:
spring:
  security:
    oauth2:
      client:
        registration:
          sso-example-app-tap-client-registration:
            client-id: xxxx
            client-secret: xxxx
            scope:
              - openid
              - profile
              - email
        provider:
          sso-example-app-tap-client-registration:
            issuer-uri: xxxx

