server:
  port: 3000

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.auth0.example: TRACE

spring:
  security:
    oauth2:
      client:
        provider:
          auth0-identity-provider:
            issuer-uri: https://auth.example.com
        registration:
          auth0-identity-provider:
            provider: appsso
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://test.example.com/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: messaging-client

