logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.auth0.example: TRACE

org:
  springframework:
    cloud:
      bindings:
        boot:
          oauth2:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: env,info,health

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: tcXPnhH0G2xrX4hD3XQihr3Tjpc1SKJA
            client-secret: b3YIHPIUu0NnnPYwEZY3WDOaAD2Hx7AkFh0mxkFBc2marTl7vQEBz0VikvSXsQn5
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: https://dev-pbi3csp88xs4ezg5.us.auth0.com/

