apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: sso-example-app-tap
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    autoscaling.knative.dev/min-scale: "1"
  name: sso-example-app-tap
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  serviceClaims:
  # this name has to match the client registration you want to use.
  - name: sso-example-app-tap-client-registration
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: sso-example-app-tap-client-registration
  source:
    git:
      url: https://github.com/x95castle1/sso-example-app-tap.git
      ref:
        branch: main
